### PR TITLE
adds alt builds for 1804 and next salt

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
removed fastly from snsalt build, kicking

**Comment by giorgiosironi** [comment]
Now failing on our custom `kong` Salt state, which needs a Python 3 upgrade?
```
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:           ID: add-plugin-acl-for-annual_reports
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:     Function: kong.post_plugin
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:         Name: acl
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:       Result: False
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:      Comment: An exception occurred in this state: Traceback (most recent call last):
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                 File "/usr/lib/python3/dist-packages/salt/state.py", line 1919, in call
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                   **cdata['kwargs'])
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                 File "/usr/lib/python3/dist-packages/salt/loader.py", line 1918, in wrapper
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                   return f(*args, **kwargs)
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                 File "/var/cache/salt/minion/extmods/states/kong.py", line 28, in post_plugin
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                   existing_plugin = _plugin(admin_api, api, name)
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                 File "/var/cache/salt/minion/extmods/states/kong.py", line 45, in _plugin
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                   matching = [plugin for plugin in json.loads(response.content)['data'] if plugin['name'] == name]
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                 File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:                   s.__class__.__name__))
[2020-03-03T07:10:40.900Z] [54.234.242.10] out:               TypeError: the JSON object must be str, not 'bytes'
```

**Comment by lsh-0** [comment]
> Now failing on our custom kong Salt state, which needs a Python 3 upgrade?

that's been fixed (see diff and `fresh`), but `base` will continue to fail. I'm trying to get `snsalt` build to pass but I'm getting permissions errors from Vault. I shouldn't be, I disabled `fastly` for this project+alt-config so something is holding on to that config. 

Will give it another kick while I inspect state of Alfred

**Comment by lsh-0** [comment]
I think the problem is this PR was built with one set of config and has had that config changed from out beneath it, leaving it with context files that are incorrect. For example, this:

    /srv/builder/.cfn/contexts/api-gateway--pr-15-fresh-snsalt.json

contains references to fastly and it's this context that is used to build the Cloudformation and Terraform templates. 

closing PR and opening a duplicate one

**Pull request closed without merging**
